<a href="https://colab.research.google.com/github/kameshcodes/deep-learning-codes/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$\textbf{Pytorch Day 1}$$

---

# 1. $\textbf{Tensor Basics}$

In [1]:
import torch

import random
random.seed(1) #for reprodicibility

## $\textbf{1.1 Tensor Creation}$

### $\text{1.1.1 Empty Tensors}$


In [2]:
x = torch.empty(1)
print(x)

tensor([1.3556e-19])


$\text{This empty tensor means it will intialize an empty tensor, basically a garbage value}$

In [3]:
x = torch.empty(3)
print(x)

tensor([8.9469e+08, 3.1681e-41, 2.1017e-21])


<br>


$\textbf{Lets make multidimensional tensor}$

In [4]:
x = torch.empty(3, 4)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 8.9602e+08, 3.1681e-41],
        [1.6450e+08, 3.1681e-41, 5.5599e-12, 4.3489e-41],
        [1.4013e-45, 0.0000e+00, 4.2039e-45, 0.0000e+00]])


In [5]:
x = torch.empty(2, 3, 4)
print(x)

tensor([[[1.0003e+09, 3.1681e-41, 1.0003e+09, 3.1681e-41],
         [2.3822e-44, 0.0000e+00, 3.4834e+05, 3.1681e-41],
         [1.0003e+09, 3.1681e-41, 2.0319e-43, 0.0000e+00]],

        [[8.9604e+08, 3.1681e-41, 1.0001e+09, 3.1681e-41],
         [1.6241e-42, 3.1681e-41, 1.0003e+09, 3.1681e-41],
         [1.9618e-44, 0.0000e+00, 1.0003e+09, 3.1681e-41]]])


### $\text{1.1.2 Tensors of zeros}$

In [6]:
y = torch.zeros(3)
print(y)

tensor([0., 0., 0.])


In [7]:
y = torch.zeros(3,4)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
y = torch.zeros(2,3,4)
print(y)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


###  $\text{1.1.3 Tensor of ones and torch dtypes}$

In [9]:
z = torch.ones(3)
print(z)

tensor([1., 1., 1.])


In [10]:
print(z.dtype)

torch.float32


$\text{By default, The datatype inside the tensors are float 32.}$



In [11]:
print(y.dtype)

torch.float32


$\text{You can see the same with tensor of zeros as well. But, We can change this}$

**Pass:** `dtype=torch.datatype`



In [12]:
z = torch.ones(3, dtype=torch.int32)
print(z)

tensor([1, 1, 1], dtype=torch.int32)


In [13]:
z = torch.ones(3, dtype=torch.double)
print(z)

tensor([1., 1., 1.], dtype=torch.float64)


In [14]:
z = torch.ones(3, dtype=torch.float32)
print(z)

tensor([1., 1., 1.])


### $\text{1.1.4 size()}$

In [15]:
z = torch.ones(3, dtype=torch.double)
print(z)

tensor([1., 1., 1.], dtype=torch.float64)


In [16]:
z.size

<function Tensor.size>

 size$\text{ does not work the was in pandas but here you write it a method like }$ `z.size()`

In [17]:
z.size()

torch.Size([3])

In [18]:
z = torch.ones(5, 3, dtype=torch.double)
z.size()

torch.Size([5, 3])

### 1.1.5 $\text{Creating Tensor for Data}$

In [19]:
list_data = [1,2,3,4]
tensor_data = torch.tensor(list_data, dtype=torch.float16) # Note: You can change type of data as well when you are converting
print(tensor_data)

tensor([1., 2., 3., 4.], dtype=torch.float16)


## $\textbf{1.2 Tensor Operations}$

#### $\text{1.2.1 Addition of Tensors}$

In [20]:
x = torch.rand(2,2) # rand create a random tensor
y = torch.ones(2,2, dtype=torch.int16) # creates a tensor of 1's

print(x)
print(y)

tensor([[0.5398, 0.7987],
        [0.4130, 0.7581]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int16)


In [21]:
z = x+y
print(z)

tensor([[1.5398, 1.7987],
        [1.4130, 1.7581]])


In [22]:
z = torch.add(x,y)
print(z)

tensor([[1.5398, 1.7987],
        [1.4130, 1.7581]])


$\text{Inplace Addition}$

In [23]:
x.add_(y)
print(x)

tensor([[1.5398, 1.7987],
        [1.4130, 1.7581]])


#### $\text{1.2.2 Substraction of Tesors}$

In [24]:
x = torch.rand(2,2) # rand create a random tensor
y = torch.ones(2,2, dtype=torch.int16) # creates a tensor of 1's

print(x)
print(y)

tensor([[0.4491, 0.9503],
        [0.7902, 0.7317]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int16)


In [25]:
z = x-y
print(z)

tensor([[-0.5509, -0.0497],
        [-0.2098, -0.2683]])


In [26]:
z = torch.sub(x,y)
print(z)

tensor([[-0.5509, -0.0497],
        [-0.2098, -0.2683]])


In [27]:
x.sub_(y)
print(x)

tensor([[-0.5509, -0.0497],
        [-0.2098, -0.2683]])


### $\text{1.2.3 ElementWise Product of Tesors}$

In [28]:
x = torch.rand(2,2) # rand create a random tensor
y = torch.ones(2,2, dtype=torch.int16) # creates a tensor of 1's

print(x)
print(y)

tensor([[0.1618, 0.1219],
        [0.6841, 0.3405]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int16)


In [29]:
z=x*y
print(z)

tensor([[0.1618, 0.1219],
        [0.6841, 0.3405]])


In [30]:
z = torch.mul(x,y)
print(z)

tensor([[0.1618, 0.1219],
        [0.6841, 0.3405]])


In [31]:
x.mul_(y)
print(x)

tensor([[0.1618, 0.1219],
        [0.6841, 0.3405]])


### 1.2.4 $\text{ElementWise Divsion of Tensors}$

In [32]:
x = torch.rand(2,2) # rand create a random tensor
y = torch.ones(2,2, dtype=torch.int16) # creates a tensor of 1's

print(x)
print(y)

tensor([[0.3684, 0.6408],
        [0.4821, 0.8244]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int16)


In [33]:
z = x/y
print(z)

tensor([[0.3684, 0.6408],
        [0.4821, 0.8244]])


In [34]:
z = torch.div(x,y)
print(z)

tensor([[0.3684, 0.6408],
        [0.4821, 0.8244]])


## $\textbf{1.3 Slicing in Tensors}$

In [35]:
x = torch.rand(5)
print(x)

tensor([0.4432, 0.6897, 0.0678, 0.0505, 0.2598])


In [36]:
x[2:]

tensor([0.0678, 0.0505, 0.2598])

In [37]:
x[:4]

tensor([0.4432, 0.6897, 0.0678, 0.0505])

$\textbf{Slicing a Multi-Dimensonal Tensors}$

In [38]:
x = torch.rand(4,5)
print(x)

tensor([[0.4295, 0.2773, 0.6252, 0.3761, 0.0166],
        [0.9451, 0.2275, 0.3956, 0.4408, 0.0978],
        [0.6994, 0.6357, 0.2643, 0.2298, 0.2416],
        [0.1883, 0.3213, 0.1317, 0.0937, 0.0543]])


In [39]:
x[1:,:3]

tensor([[0.9451, 0.2275, 0.3956],
        [0.6994, 0.6357, 0.2643],
        [0.1883, 0.3213, 0.1317]])

In [40]:
x[2:4,3:5]

tensor([[0.2298, 0.2416],
        [0.0937, 0.0543]])

#### $\text{1.3.1 Indexing in tensor}$

In [41]:
x[0,0]

tensor(0.4295)

$\textbf{Getting the item at indexed element}$

In [42]:
x[0,0].item()

0.4294775724411011

## $\textbf{1.4 Resize a Tensor}$

In [43]:
x = torch.rand(4,4)
print(x)

tensor([[0.0877, 0.2904, 0.4533, 0.2837],
        [0.6637, 0.1898, 0.6594, 0.3428],
        [0.7833, 0.9994, 0.5927, 0.1450],
        [0.0848, 0.2985, 0.0353, 0.8597]])


In [44]:
y = x.view(16)
y

tensor([0.0877, 0.2904, 0.4533, 0.2837, 0.6637, 0.1898, 0.6594, 0.3428, 0.7833,
        0.9994, 0.5927, 0.1450, 0.0848, 0.2985, 0.0353, 0.8597])

In [45]:
y = x.view(-1,2) # -1 gives it the required value for reshaping
print(y)

tensor([[0.0877, 0.2904],
        [0.4533, 0.2837],
        [0.6637, 0.1898],
        [0.6594, 0.3428],
        [0.7833, 0.9994],
        [0.5927, 0.1450],
        [0.0848, 0.2985],
        [0.0353, 0.8597]])


## $\textbf{1.5 Numpy <=> Tensor}$

### $\text{1.5.1 Numpy => Tensor}$

In [46]:
import torch
import numpy as np

In [47]:
x = torch.rand(5)
print(x)
print(type(x))

tensor([0.7557, 0.0426, 0.3838, 0.7056, 0.4060])
<class 'torch.Tensor'>


In [48]:
p = x.numpy()
print(p)
print(type(p))

[0.7557136  0.04258299 0.38379508 0.7055826  0.40597737]
<class 'numpy.ndarray'>


$\textbf{Caution !}$

$\text{Since, our tensor is on CPU and not GPU, both object x and p shares same memory location, then changing one will change other.}$

In [49]:
x.add_(1)
print(x)

tensor([1.7557, 1.0426, 1.3838, 1.7056, 1.4060])


In [50]:
print(p)

[1.7557136 1.042583  1.383795  1.7055826 1.4059774]


$\text{Notice that: Changing 'x' also changed 'p' because they are sharing same memory location}$

### $\textbf{1.5.2 Numpy <= Tensor}$

In [51]:
a = np.random.randn(5)
print(a)
print(type(a))

[ 1.72715392  1.60455755 -0.61586124 -0.21554612 -0.60673465]
<class 'numpy.ndarray'>


In [52]:
x = torch.from_numpy(a)
print(x)
print(type(x))

tensor([ 1.7272,  1.6046, -0.6159, -0.2155, -0.6067], dtype=torch.float64)
<class 'torch.Tensor'>


### Note: Changing dtype of a tensor

In [53]:
print("Before:")
print(x)
x=x.to(dtype=torch.float16)
print("\nAfter:")
print(x)

Before:
tensor([ 1.7272,  1.6046, -0.6159, -0.2155, -0.6067], dtype=torch.float64)

After:
tensor([ 1.7275,  1.6045, -0.6157, -0.2156, -0.6069], dtype=torch.float16)


## $\textbf{1.6 Creating Tensors on CUDA GPU}$

In [54]:
torch.cuda.is_available()

True

In [55]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  # create directly on GPU
  x = torch.ones(5, device = device)
  # create on cpu then move to GPU
  y = torch.zeros(5)
  y = y.to(device=device)
  z = x+y
  z.numpy() #this will give error coz numpy can handle only cpu tensor

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [56]:
if torch.cuda.is_available():
  device = torch.device("cuda")

  x = torch.ones(5, device = device)
  y = torch.zeros(5)
  y = y.to(device=device)

  z = x+y
  print(z)
  z = z.to(device=torch.device("cpu"))
  print(z)
  z = z.numpy()
  print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
